QuanLyBanHang/QuanLyBanHang_Client/Controllers/CartController.cs
using Repository.Models;
using Repository.ViewModels;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyBanHang.Controllers
{
    public class CartController : Controller
    {
        private ProductService _service;
        public CartController()
        {
            _service = new ProductService();
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Buy(int id, int quantity, bool isCombo)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                Item item = null;
                if(!isCombo)
                {
                    //find product in db
                    Product product = _service.getProductById(id);
                    if(product == null)
                    {
                        return Json(new { message = "Không tồn tại sản phẩm", success = false, JsonRequestBehavior.AllowGet });
                    } else
                    {
                        //check stock of product 
                        if (quantity > product.Stock)
                        {
                            return Json(new { message = "Số lượng sản phẩm tồn kho hiện không đủ để thực hiện giao dịch", success = false, JsonRequestBehavior.AllowGet });
                        }

                        // create item before add in list cart
                        item = new Item
                        {
                            Product = product,
                            Quantity = quantity,
                            isCombo = false
                           
                        };
                    }
                } else
                {

                    // find combo in db
                    Combo combo = _service.getComboById(id);

                    if(combo == null)
                    {
                        return Json(new { message = "Không tồn tại sản phẩm trong csdl", success = false, JsonRequestBehavior.AllowGet });
                    } else
                    {
                        // check quantity of combo validate
                        if(!_service.checkQuantityProductOfCombo(combo, quantity))
                        {
                            return Json(new { message = "Số lượng sản phẩm không đủ để đặt combo", success = false, JsonRequestBehavior.AllowGet });
                        }

                        //create new item to add in list cart
                        item = new Item
                        {
                            Combo = combo,
                            Quantity = quantity,
                            isCombo = true
                        };
                    }
                }
                cart.Add(item);
                Session["cart"] = cart;
                return Json(new { message = "Thêm sản phẩm thành công", success = true, JsonRequestBehavior.AllowGet });
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id, isCombo);
                if (index != -1)
                {
                    cart[index].Quantity = cart[index].Quantity + quantity;
                    int quantityItem = cart[index].Quantity;
                    if(isCombo)
                    {
                        // check quantity of combo validate
                        if (!_service.checkQuantityProductOfCombo(cart[index].Combo, quantityItem))
                        {
                            cart[index].Quantity = cart[index].Quantity - quantity;
                            return Json(new { message = "Số lượng sản phẩm không đủ để đặt combo", success = false, JsonRequestBehavior.AllowGet });
                        }
                        
                    } else
                    {
                        // check quantity of product validate
                        var product = _service.getProductById(id);
                        if(product == null )
                        {
                            return Json(new { message = "Số lượng sản phẩm không đủ để đặt combo", success = false, JsonRequestBehavior.AllowGet });
                        } else
                        {
                            if (product.Stock < quantityItem)
                            {
                                cart[index].Quantity = cart[index].Quantity - quantity;
                                return Json(new { message = "Số lượng sản phẩm tồn kho hiện không đủ để thực hiện giao dịch", success = false, JsonRequestBehavior.AllowGet });
                            }
                        }
                    }
                }
                else
                {
                    if(isCombo)
                    {
                        Combo combo = _service.getComboById(id);
                        if(combo == null)
                        {
                            return Json(new { message = "Combo không tồn tại", success = false, JsonRequestBehavior.AllowGet });
                        } else
                        {
                            if (!_service.checkQuantityProductOfCombo(combo, quantity))
                            {
                                return Json(new { message = "Số lượng sản phẩm không đủ để đặt combo", success = false, JsonRequestBehavior.AllowGet });
                            }
                            else
                            {
                                cart.Add(new Item
                                {
                                    Combo = combo,
                                    Quantity = quantity,
                                    isCombo = true
                                });
                            }
                        }
                       
                    }  else
                    {
                        Product product = _service.getProductById(id);
                        if(product == null)
                        {
                            return Json(new { message = "Không tồn tại sản phẩm", success = false, JsonRequestBehavior.AllowGet });
                        } else
                        {
                            if (product.Stock < quantity)
                            {
                                return Json(new { message = "Số lượng sản phẩm không đủ", success = false, JsonRequestBehavior.AllowGet });
                            }
                            else
                            {
                                cart.Add(new Item
                                {
                                    Product = product,
                                    Quantity = quantity,
                                    isCombo = false
                                });
                            }
                        }
                       
                    }
                   
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(int id, bool isCombo)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id, isCombo);
            if(index != -1)
            {
                cart.RemoveAt(index);
                if(cart.Count <= 0)
                {
                    Session["cart"] = null;
                } else
                {
                    Session["cart"] = cart;
                }
                return Json(new { message = "Xóa sản phẩm thành công", success = true });
            }
            return Json(new { message = "Xóa sản phẩm thất bại", success = false });
        }

        [HttpPost]
        public ActionResult UpdateCart(int id, int quantity, bool isCombo)
        {
            // update cart
            if(Session["cart"] == null)
            {
                return Json(new { message = "Vui đăng thêm sản phẩm trước khi thanh toán", sucess = false });
            } else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id, isCombo);
                var oldQuantity = cart[index].Quantity;
                var newQuantity = quantity;

                if (index != -1)
                {
                    if (isCombo)
                    {
                        // check quantity of combo validate
                        if (!_service.checkQuantityProductOfCombo(cart[index].Combo, newQuantity))
                        {
                            return Json(new { message = "Số lượng sản phẩm không đủ để đặt combo", success = false, value = oldQuantity, JsonRequestBehavior.AllowGet });
                        }

                    }
                    else
                    {
                        // check quantity of product validate
                        var product = _service.getProductById(id);
                        if(product == null)
                        {
                            return Json(new { message = "Số lượng sản phẩm tồn kho hiện không đủ để thực hiện giao dịch", success = false, value = oldQuantity, JsonRequestBehavior.AllowGet });
                        } else
                        {

                            if (product.Stock < newQuantity)
                            {
                                return Json(new { message = "Số lượng sản phẩm tồn kho hiện không đủ để thực hiện giao dịch", success = false, value = oldQuantity, JsonRequestBehavior.AllowGet });
                            }
                        }
                       
                    }
                }

                //udapte cart item when validate
                cart[index].Quantity = newQuantity;
                Session["cart"] = cart;

QuanLyBanHang/QuanLyBanHang_Client/Controllers/OrderController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repository.ViewModels;

namespace QuanLyBanHang_Client.Controllers
{
    public class OrderController : Controller
    {
        private InvoiceService _service;

        public OrderController()
        {
            _service = new InvoiceService();
        }

        // GET: Order
        public ActionResult Index(int? customerId)
        {
            if(Session["username"] == null || customerId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TrackingOrderModel trackingOrder = _service.getOrdersOfCustomer(customerId.GetValueOrDefault());
            return View(trackingOrder);
        }


        [HttpPost]
        public ActionResult getInvoiceDetail(int invoiceId)
        {

            if (Session["username"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            InvoiceDetailItemModel model = _service.getInvoiceDetail(invoiceId);
            return PartialView("_InvoiceDetail", model);
        }

    }
}

QuanLyBanHang/QuanLyBanHang_Client/Controllers/ProductController.cs
using Repository.Models;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyBanHang_Client.Controllers
{
    public class ProductController : Controller
    {
        private ProductService _service;
        public ProductController()
        {
            _service = new ProductService();
        }
      
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id == null) return null;
            Product product = _service.getProductById(id);
            return View(product);
        }

        public ActionResult ComboDetail(int? id)
        {
            if (id == null) return null;
            Combo combo = _service.getComboById(id);
            return View(combo);
        }
    }
}

QuanLyBanHang/QuanLyBanHang_Client/Views/Shared/_Combo.cshtml
@model IEnumerable<Repository.Models.Combo>
<!-- container -->
<div class="container">
    <!-- row -->
    <div class="row">
        <!-- section title -->
        <div class="col-md-12">
            <div class="section-title">
                <h3 class="title">Danh sách combo</h3>
            </div>
        </div>
        <!-- /section title -->
        <!-- Products tab & slick -->
        <div class="col-md-12">
            <div class="row">
                <div class="products-tabs">
                    <!-- tab -->
                    <div id="tab1" class="tab-pane fade in active">
                        <div class="products-slick" data-nav="#slick-nav-1">
                            @foreach (var item in Model)
                            {
                                var imgUrl = "/Content/img/" + @item.C_Image;
                                <div class="product">
                                    <input type="hidden" id="@item.Id" />
                                    <div class="product-img">
                                        <img src=@Url.Content(@imgUrl) alt="">
                                        <div class="product-label">
                                            <span class="new">NEW</span>
                                        </div>
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">Danh mục</p>
                                        <h3 class="product-name">@Html.ActionLink(@item.ComboName, "ComboDetail", "Product", new { id = @item.Id }, null)</h3>
                                        <h4 class="product-price">@item.Total.ToString("N0")đ</h4>
                                        @*<div class="product-btns">
                                            <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                            <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                            <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                                        </div>*@
                                    </div>
                                    <div class="add-to-cart">
                                        <button class="add-to-cart-btn btnAddToCart1" data-productId="@item.Id.ToString()"><i class="fa fa-shopping-cart"></i> Thêm vào giỏ hàng</button>
                                    </div>
                                </div>
                            }
                        </div>
                        <div id="slick-nav-1" class="products-slick-nav"></div>
                    </div>
                    <!-- /tab -->
                </div>
            </div>
        </div>
        <!-- Products tab & slick -->
    </div>
    <!-- /row -->
</div>
<!-- /container -->
<script>
    $(document).ready(function () {
        var reloadJsFile = function () {
            $("script").each(function () {
                var oldScript = this.getAttribute("src");
                if (oldScript == "/Content/js/main.js") {
                    $(this).remove();
                    var newScript;
                    newScript = document.createElement('script');
                    newScript.type = 'text/javascript';
                    newScript.src = oldScript;
                    $("#scriptDisplay").append(newScript);
                }
            });
        }
        reloadJsFile()
        //$(".slider").not('.slick-initialized').slick()

        //add item to cart
        //add to cart
        $(".btnAddToCart1").on('click', function (event) {
            const startTime = performance.now();
            event.preventDefault();
            var productId = $(this).attr('data-productId');
            $.ajax({
                type: "Post",
                url: "/Cart/Buy",
                data: { id: productId, quantity: 1, isCombo: true },
                success: function (response) {
                    if (response.success) {
                        alert(response.message)
                        const duration = performance.now() - startTime;
                        console.log(`request add item to cart took ${duration}ms`);
                        location.reload();
                    } else {
                        alert(response.message)
                    }
                },
                error: function (response) {
                    alert("Thêm sản phẩm thành công")
                    location.reload();
                }
            })
        })
    })
</script>

QuanLyBanHang/QuanLyBanHang_Client/Views/Shared/_Header.cshtml
@{
    string username = null;
}
@if (Session["username"] != null)
{
    username = Session["username"].ToString();
}
<input type="hidden" id="txtSession" value="@username" />

<header>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container">
            <ul class="header-links pull-left">
                <li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
                <li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
                <li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
            </ul>
            <ul class="header-links pull-right">
                <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                @if (Session["username"] == null)
                {
                    <li><a data-toggle="modal" href="#loginAndRegisterModal"><i class="fa fa-user-o"></i>Đăng nhập</a></li>
                }
                else
                {
                    var customerId = Session["customerId"].ToString();
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-o"></i> @Session["Name"]
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="margin-left:15px">
                            <li class="dropdown-item"><a href="@Url.Action("Index", "Order", new { customerId = customerId })" style="color: black;margin-left:20px">Đơn hàng của tôi</a></li>
                            <li class="dropdown-item"><a href="@Url.Action("Logout","Account")" style="color: black;margin-left:40px">Đăng xuất</a></li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
    </div>
    <!-- /TOP HEADER -->
    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a href="@Url.Action("Index","Home")" class="logo">
                            <img src=@Url.Content("/Content/img/logo.png") alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->
                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">
                        <form>
                            <input class="input" id="txtSearchString" placeholder="Nhập tên sản phẩm....">
                            <button id="btnFilter" class="search-btn">Tìm kiếm</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->
                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix">
                    <div class="header-ctn">
                        @{

                            var carts = Session["cart"] != null ? (List<Repository.ViewModels.Item>)Session["cart"] : null;
                            double total = 0;
                            var cartSize = 0;
                        }
                        <div class="dropdown">
                            @if (Session["cart"] == null || @carts == null)
                            {
                                <a class="dropdown-toggle" href="" data-toggle="tooltip" title="Chưa có sản phẩm nào trong giỏ hàng" aria-expanded="true">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span>Giỏ hàng</span>
                                    <div class="qty" id="quantityItemCart">0</div>
                                </a>
                            }
                            else
                            {
                                <a class="dropdown-toggle" href="" data-toggle="dropdown" aria-expanded="true">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span>Giỏ hàng</span>
                                    <div class="qty" id="quantityItemCart">0</div>
                                </a>
                            }
                           
                            @if (Session["cart"] != null && @carts != null)
                            {
                                if (carts.Count > 0)
                                {
                                    <div class="cart-dropdown">
                                        <div class="cart-list">
                                            @foreach (var item in carts)
                                            {
                                                if (!item.isCombo)
                                                {
                                                    var img = "/Content/img/" + item.Product.C_Image;
                                                    double amount = item.Product.Price * item.Quantity;
                                                    <div class="product-widget">
                                                        <div class="product-img">
                                                            <img src=@Url.Content(@img) alt="">
                                                        </div>
                                                        <div class="product-body">
                                                            <h3 class="product-name">@Html.ActionLink(item.Product.ProductName, "Detail", "Product", new { id = @item.Product.Id }, null)</h3>
                                                            <h4 class="product-price"><span class="qty">@item.Quantity.ToString()x</span>@item.Product.Price.ToString("N0")đ</h4>
                                                             <h4 class="product-price"><span class="qty">Thành tiền: <br />
                                                             </span>@amount.ToString("N0")đ</h4>
                                                        </div>
                                                        <button class="delete" data-isCombo="@item.isCombo" data-productId="@item.Product.Id"><i class="fa fa-close"></i></button>
                                                    </div>

                                                    total += amount;
                                                    cartSize += item.Quantity;
                                                }
                                                else
                                                {
                                                    var img = "/Content/img/" + item.Combo.C_Image;
                                                    var amount = item.Combo.Total * item.Quantity;
                                                    <div class="product-widget">
                                                        <div class="product-img">
                                                            <img src=@Url.Content(@img) alt="">
                                                        </div>
                                                        <div class="product-body">
                                                            <h3 class="product-name">@Html.ActionLink(@item.Combo.ComboName, "ComboDetail", "Product", new { id = @item.Combo.Id }, null)</h3>
                                                            <h4 class="product-price"><span class="qty">@item.Quantity.ToString()x</span>@item.Combo.Total.ToString("N0")đ</h4>
                                                            <h4 class="product-price"><span class="qty">Thành tiền:<br/></span>@item.Combo.Total.ToString("N0")đ</h4>
                                                        </div>
                                                        <button class="delete"  data-isCombo="@item.isCombo" data-productId="@item.Combo.Id"><i class="fa fa-close"></i></button>
                                                    </div>
                                                    total += amount;
                                                    cartSize += item.Quantity;
                                                }
                                            }

                                        </div>
                                        <div class="cart-summary">
                                            <small>@cartSize (Sản phẩm) được thêm vào giỏ hàng</small>
                                            <h5>Tổng tiền: @total.ToString("N0")đ</h5>
                                        </div>
                                        <input type="hidden" value="@cartSize" id="productNumber" />
                                        <div class="cart-btns">
                                            @Html.ActionLink("Xem giỏ hàng", "Detail", "Cart", null, null)
                                            <a href="#" id="btnCheckout">Thanh toán<i class="fa fa-arrow-circle-right"></i></a>
                                        </div>
                                    </div>
                                }

                            }

                        </div>
                        <!-- /Cart -->
                        <!-- Menu Toogle -->
                        <div class="menu-toggle">
                            <a href="#">
                                <i class="fa fa-bars"></i>
                                <span>Menu</span>
                            </a>
                        </div>
                        <!-- /Menu Toogle -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->

<div class="container modal fade" id="loginAndRegisterModal" role="dialog">
    <div class="row">
        @Html.Partial("_loginAndRegister")
    </div>
</div>

<script>
    //drop down menu
    $(document).ready(function () {
        $(".dropdown-toggle").dropdown();
        var productNumber = $("#productNumber").val();
        $("#quantityItemCart").html(productNumber)

        //remove cart item 
        $(".delete").on('click', function () {
            var productId = $(this).attr("data-productId")
            var isCombo = $(this).attr("data-isCombo")
            var isComfirm = confirm("Bạn có chắc muốn xóa sản phẩm?")
            if (isComfirm) {
                $.ajax({
                    type: "Post",
                    url: "/Cart/Remove",
                    data: { id: productId, isCombo: isCombo },
                    success: function (response) {
                        if (response.success) {
                            alert(response.message)
                            location.reload();
                        } else {
                            alert(response.message)
                        }
                    },
                    error: function (response) {
                        console.log(reponse)
                    }
                })
            }
        })

        //checkout
        $("#btnCheckout").on('click', function () {
            var session = $("#txtSession").val();
            if (session == "") {
                alert("Vui lòng đăng nhập trước khi thanh toán")
            } else {
                window.location.href = "/Cart/Checkout";
            }
        })

        //tracking my order

       
    });
</script>

QuanLyBanHang/QuanLyBanHang_Client/Views/Shared/_InvoiceDetail.cshtml
@{
    var model = Model as Repository.ViewModels.InvoiceDetailItemModel;
    var invoiceDetail_Combo = model.invoiceDetailCombo;
    var invoiceDetail_Product = model.invoiceDetailProduct;
}
<table class="table table-responsive table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                Hình ảnh
            </th>
            <th>
                Tên sản phẩm
            </th>
            <th style="text-align:center">
                Đơn giá
            </th>
            <th style="text-align: center">
                Số lượng
            </th>
            <th style="text-align: center">
                Thành tiền
            </th>
        </tr>
    </thead>
    <tbody>

        @if (invoiceDetail_Product.Count() > 0)
        {
            foreach (var item in invoiceDetail_Product)
            {
                var imgUrl = "/Content/img/" + item.Product.C_Image;
                <tr>
                    <td style="vertical-align:middle">
                        <img src=@Url.Content(imgUrl) style="width:50px; height:50px" />
                    </td>
                    <td style="vertical-align:middle">
                       @item.Product.ProductName
                    </td>
                    <td style="vertical-align:middle;text-align: center ">
                        @item.UnitPrice.ToString("N0")đ
                    </td>
                    <td style="vertical-align:middle; text-align: center">
                        @item.Quantity
                    </td>
                    <td style="vertical-align:middle; text-align: center">
                        @item.Amount.ToString("N0")đ
                    <td>
                </tr>
            }
         }

        @if (invoiceDetail_Combo.Count() > 0)
        {
            foreach (var item in invoiceDetail_Combo)
            {
                var imgUrl = "/Content/img/" + item.Combo.C_Image;
                <tr>
                    <td style="vertical-align:middle">
                        <img src=@Url.Content(imgUrl) style="width:50px; height:50px" />
                    </td>
                    <td style="vertical-align:middle">
                        @item.Combo.ComboName
                    </td>
                    <td style="vertical-align:middle; text-align: center">
                        @item.UnitPrice.ToString("N0")đ
                    </td>
                    <td style="vertical-align:middle; text-align: center">
                        @item.Quantity
                    </td>
                    <td style="vertical-align:middle; text-align: center">
                        @item.Amount.ToString("N0")đ
                    <td>
                </tr>
            }
        }

        @if(invoiceDetail_Product == null && invoiceDetail_Product == null)
        {
            <tr>
                <td colspan="5" style="text-align:center"><i>Không tìm thấy chi tiết của sản phẩm</i></td>
            </tr>
        }
    </tbody>
</table>